security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js|uploads)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            logout:
                path: app_logout

            custom_authenticator:
                - App\Security\ApiTokenAuthenticator

            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800

    access_control:
         - { path: ^/api, roles: ROLE_API }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
